apiVersion: v1
kind: Namespace
metadata:
  name: comfyui
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-model-pvc
  namespace: comfyui
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 100Gi